title: O-COCOSDA 2026
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://ococosda2026.github.io/test

logo: "images/ococosda-logo.png"

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
